### ISSUE TITLE
Can't use in Vite: Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. 

### ISSUE THREAD

**Issue by VityaSchel** [alexgorbatchev/crc#82]
Getting this error because Vite polyfills buffer:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'from')
    at createBuffer (create_buffer.js:4:50)
    at Function.result [as unsigned] (define_crc.js:3:52)
```

**Comment by VityaSchel** [comment]
solution: install buffer
